#!/usr/bin/env bash
# Groups visitors by IP and HTTP status code, ordered by number of occurrences

awk '{count[$1 " " $9]++} END {for (k in count) printf "%7d %s\n", count[k], k}' apache-access.log | sort -rn
