#!/usr/bin/ env bash 
# displaying "Best School" 10 times and on 9th time the code displays "HI"on a new line
 
i=1
while [ "$i" -le 10 ];do
  echo "Best School"
    if [ "$i" -eq 9 ];then
    echo "Hi"
    fi
 i=$((i+1))
done
