#!/usr/bin/env bash
#displaying "Best School" with additional displays of "bad luck" and "good luck" but by interupting the loop
count=1
while [ "$count" -le 10 ];do
if [ "$count" -eq 4 ];then
  echo "bad luck"
  echo "Best School"
elif [ "$count" -eq 8 ];then
  echo "good luck"
  echo "Best School"
else
  echo "Best School"
fi
  count=$((count+1))
done
