#!/usr/bin/env bash
# a script that uses while loop together with the case statements
n=1
while [ "$n" -le 20 ];do
    echo "$n" 
case "$n" in
 4)
 echo "bad luck from China"
;;
 9)
 echo "bad luck from Japan"
;;
 17)
 echo "bad luck from Italy"
;;

  *)
  
;;

 esac 
n=$((n+1))
done
