#!/usr/bin/env bash 
#script displaying 12 hours and 59  minutes 

hours=0

while [ "$hours" -le 12 ]
do
     echo "Hour: $hours"
      minute=1
while [ "$minute" -le 59 ]
do
     echo "$minute"
     ((minute++))
done
     ((hours++))
done
